#!/usr/bin/env python3

# ROS Node for Emlid M+ GPS device outputting NMEA sentences over a USB serial connection

from this import d
import pyudev
import serial
import rospy
import glob
import reach_ros_node.driver  # uses package from https://github.com/rpng/reach_ros_node


if __name__ == '__main__':
    """Main Function."""


    rospy.logdebug("Starting Emlid M+ Node")
    rospy.init_node('emlid_m_plus_node', anonymous=True)

    port = ''
    emlid = serial.Serial()

    device_connected = False

    # Get a list of all devices over USB and find device by using Vendor name

    context = pyudev.Context()

    for device in context.list_devices(subsystem='tty', ID_BUS='usb'):
        device_details = dict(device)

        if device_details['ID_VENDOR'] == 'Emlid': 
            port = str(device_details['DEVNAME'])

            rospy.logdebug("Emlid device found at port = " + port)

            try:
                emlid = serial.Serial(port=port, baudrate=38400)
                device_connected = True
                break

            except Exception as e:
                rospy.logerr('Emlid serial connection attempt failed: ')
                rospy.logerr(e)

    if device_connected:
        emlid_driver = reach_ros_node.driver.RosNMEADriver()

        while not rospy.is_shutdown():
                data = emlid.readline()

                data = str(data, 'ascii')
                
                data = data.rstrip()

                try:
                    emlid_driver.process_line(data)
                except ValueError as e:
                    rospy.logerr("GPS Emlid: Value error, likely due to missing fields in the NMEA message or loss of GPS fix. Error was: %s." % e)

